import type { Metadata,Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VitaNova",
  description: "Generated by create next app",
appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "VitaNova",
  },

};
//view port theme configuration

export const viewport: Viewport = {
  themeColor: "#dc2626",
   width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
