# Generated by Django 6.0.6 on 2026-07-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitanovaAPI', '0001_initial'),
    ]

    operations = [
    ]
from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("vitanovaAPI", "Role")

    roles = [
        "Admin",
        "Donor",
        "Patient",
        "Hospital",
        "Blood Bank",
    ]

    for role_name in roles:
        Role.objects.get_or_create(
            role_name=role_name
        )


def remove_roles(apps, schema_editor):
    Role = apps.get_model("vitanovaAPI", "Role")

    Role.objects.filter(
        role_name__in=[
            "Admin",
            "Donor",
            "Patient",
            "Hospital",
            "Blood Bank",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("vitanovaAPI", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_roles,
            remove_roles
        ),
    ]